// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGssnT_x6cMQe075w_n2KxPD-hRVBi5BE',
    appId: '1:848438886124:web:42e20ab324f810bf812fc9',
    messagingSenderId: '848438886124',
    projectId: 'wildpoly-76a66',
    authDomain: 'wildpoly-76a66.firebaseapp.com',
    storageBucket: 'wildpoly-76a66.appspot.com',
    measurementId: 'G-PPN92ZZDHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5cmdLvjEr4wP7C4PvhaIXKb_WUEqGALE',
    appId: '1:848438886124:android:cf6b3fdbdecf762e812fc9',
    messagingSenderId: '848438886124',
    projectId: 'wildpoly-76a66',
    storageBucket: 'wildpoly-76a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKPtE6F2fhk2RD8r7L1YckYJJHc_D31E',
    appId: '1:848438886124:ios:eea5282d5e4b8b87812fc9',
    messagingSenderId: '848438886124',
    projectId: 'wildpoly-76a66',
    storageBucket: 'wildpoly-76a66.appspot.com',
    iosClientId: '848438886124-2go63be0qkajnmhnsfr05jmbqoddre0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildpoly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmKPtE6F2fhk2RD8r7L1YckYJJHc_D31E',
    appId: '1:848438886124:ios:1a3f7225fc8f8959812fc9',
    messagingSenderId: '848438886124',
    projectId: 'wildpoly-76a66',
    storageBucket: 'wildpoly-76a66.appspot.com',
    iosClientId: '848438886124-a5b1m93gvorprdn4krqt12k5fo0kmh8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildpoly.RunnerTests',
  );
}
